export interface Seller {
  id: string;
  name: string;
  company: string;
  avatar: string;
  rating: number;
  reviewCount: number;
  memberSince: number;
  verified: boolean;
  location: string;
  totalSales: number;
  impactKg: number;
}

export interface Listing {
  id: string;
  title: string;
  description: string;
  category: string;
  condition: "New Surplus" | "Lightly Used" | "As-Is" | "Salvage";
  price: number;
  originalPrice?: number;
  isFree: boolean;
  quantity: number;
  unit: string;
  images: string[];
  seller: Seller;
  location: string;
  distance: number;
  specs: Record<string, string>;
  pickupAvailable: boolean;
  deliveryAvailable: boolean;
  shippingAvailable: boolean;
  deliveryCost?: number;
  shippingCost?: number;
  savedCount: number;
  viewCount: number;
  listedAt: string;
  status: "active" | "paused" | "sold";
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  count: number;
  image: string;
}

export interface Order {
  id: string;
  orderNumber: string;
  items: { listing: Listing; quantity: number }[];
  buyer: { name: string; email: string; avatar: string };
  seller: Seller;
  status: "pending" | "confirmed" | "ready" | "completed" | "cancelled";
  total: number;
  serviceFee: number;
  createdAt: string;
  logistics: "pickup" | "delivery" | "shipping";
}

export const sellers: Seller[] = [
  {
    id: "s1",
    name: "Marcus Chen",
    company: "Pacific Northwest Builders",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    rating: 4.9,
    reviewCount: 127,
    memberSince: 2023,
    verified: true,
    location: "Portland, OR",
    totalSales: 45200,
    impactKg: 2340,
  },
  {
    id: "s2",
    name: "Sarah Mitchell",
    company: "Mitchell & Sons Construction",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face",
    rating: 4.8,
    reviewCount: 89,
    memberSince: 2022,
    verified: true,
    location: "Brooklyn, NY",
    totalSales: 78500,
    impactKg: 4120,
  },
  {
    id: "s3",
    name: "David Okonkwo",
    company: "Greenway Renovations",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face",
    rating: 4.7,
    reviewCount: 56,
    memberSince: 2024,
    verified: false,
    location: "Austin, TX",
    totalSales: 23100,
    impactKg: 1560,
  },
  {
    id: "s4",
    name: "Elena Rodriguez",
    company: "Rodriguez Commercial Group",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    rating: 5.0,
    reviewCount: 203,
    memberSince: 2021,
    verified: true,
    location: "Miami, FL",
    totalSales: 156000,
    impactKg: 8900,
  },
  {
    id: "s5",
    name: "James Park",
    company: "Park Design Build",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    rating: 4.6,
    reviewCount: 34,
    memberSince: 2024,
    verified: true,
    location: "Seattle, WA",
    totalSales: 12800,
    impactKg: 890,
  },
  {
    id: "s6",
    name: "Anna Kowalski",
    company: "Kowalski Interiors",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop&crop=face",
    rating: 4.8,
    reviewCount: 72,
    memberSince: 2023,
    verified: true,
    location: "Chicago, IL",
    totalSales: 34500,
    impactKg: 2100,
  },
  {
    id: "s7",
    name: "Roberto Vasquez",
    company: "Vasquez Heavy Construction",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop&crop=face",
    rating: 4.5,
    reviewCount: 41,
    memberSince: 2023,
    verified: false,
    location: "Denver, CO",
    totalSales: 19700,
    impactKg: 3200,
  },
  {
    id: "s8",
    name: "Lisa Thompson",
    company: "Thompson Remodeling Co.",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=face",
    rating: 4.9,
    reviewCount: 95,
    memberSince: 2022,
    verified: true,
    location: "San Francisco, CA",
    totalSales: 67300,
    impactKg: 5400,
  },
];

export const categories: Category[] = [
  { id: "lumber", name: "Lumber & Wood", icon: "TreePine", count: 1240, image: "https://images.unsplash.com/photo-1520869562399-e772f042f422?w=600&h=400&fit=crop" },
  { id: "steel", name: "Steel & Metal", icon: "Construction", count: 876, image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop" },
  { id: "concrete", name: "Concrete & Masonry", icon: "Blocks", count: 654, image: "https://images.unsplash.com/photo-1590412200988-a436970781fa?w=600&h=400&fit=crop" },
  { id: "electrical", name: "Electrical", icon: "Zap", count: 432, image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=600&h=400&fit=crop" },
  { id: "plumbing", name: "Plumbing", icon: "Droplets", count: 389, image: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&h=400&fit=crop" },
  { id: "fixtures", name: "Fixtures & Hardware", icon: "Wrench", count: 567, image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop" },
  { id: "roofing", name: "Roofing", icon: "Home", count: 298, image: "https://images.unsplash.com/photo-1632759145351-1d592919f522?w=600&h=400&fit=crop" },
  { id: "tile", name: "Tile & Stone", icon: "LayoutGrid", count: 723, image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop" },
  { id: "insulation", name: "Insulation", icon: "Thermometer", count: 187, image: "https://images.unsplash.com/photo-1607400201889-565b1ee75f8e?w=600&h=400&fit=crop" },
  { id: "paint", name: "Paint & Finishes", icon: "Paintbrush", count: 456, image: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=600&h=400&fit=crop" },
  { id: "doors", name: "Doors & Windows", icon: "DoorOpen", count: 345, image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop" },
  { id: "equipment", name: "Heavy Equipment", icon: "Truck", count: 123, image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop" },
];

export const listings: Listing[] = [
  {
    id: "1",
    title: "Douglas Fir 2×6 Framing Lumber — 12ft Lengths",
    description: "Premium Douglas Fir dimensional lumber, surplus from a commercial framing project. Never exposed to weather, stored indoors. Straight, clean cuts, no splits or warping. Perfect for framing, decking, or structural applications. We over-ordered by about 200 pieces and need to move them quickly.",
    category: "lumber",
    condition: "New Surplus",
    price: 4.75,
    originalPrice: 9.50,
    isFree: false,
    quantity: 186,
    unit: "piece",
    images: [
      "https://images.unsplash.com/photo-1520869562399-e772f042f422?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1541123603104-512919d6a96c?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop",
    ],
    seller: sellers[0],
    location: "Portland, OR",
    distance: 3.2,
    specs: { Material: "Douglas Fir", Dimensions: '2" × 6" × 12\'', Grade: "#2 & Better", Treatment: "Untreated", "Moisture Content": "19% or less" },
    pickupAvailable: true,
    deliveryAvailable: true,
    shippingAvailable: false,
    deliveryCost: 75,
    savedCount: 43,
    viewCount: 312,
    listedAt: "2026-02-25",
    status: "active",
  },
  {
    id: "2",
    title: "Reclaimed Red Oak Hardwood Flooring",
    description: "Beautiful reclaimed red oak flooring salvaged from a 1920s warehouse renovation. Character-rich with nail holes and natural patina. Tongue and groove, ready to install. Each plank has unique grain patterns and warm amber tones that new wood simply can't replicate.",
    category: "lumber",
    condition: "Lightly Used",
    price: 6.25,
    originalPrice: 14.00,
    isFree: false,
    quantity: 340,
    unit: "sq ft",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1520869562399-e772f042f422?w=800&h=600&fit=crop",
    ],
    seller: sellers[1],
    location: "Brooklyn, NY",
    distance: 2.4,
    specs: { Material: "Red Oak", Type: "Tongue & Groove", Width: '5"', Thickness: '3/4"', Finish: "Unfinished" },
    pickupAvailable: true,
    deliveryAvailable: true,
    shippingAvailable: true,
    deliveryCost: 120,
    shippingCost: 250,
    savedCount: 89,
    viewCount: 567,
    listedAt: "2026-02-23",
    status: "active",
  },
  {
    id: "3",
    title: "Structural Steel I-Beams W8×31",
    description: "Wide flange structural steel I-beams, surplus from a commercial renovation project. ASTM A992 grade, mill certified. Clean condition, minimal surface rust. Ideal for structural support, mezzanine construction, or residential steel framing.",
    category: "steel",
    condition: "New Surplus",
    price: 185.00,
    originalPrice: 340.00,
    isFree: false,
    quantity: 24,
    unit: "piece",
    images: [
      "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1590412200988-a436970781fa?w=800&h=600&fit=crop",
    ],
    seller: sellers[6],
    location: "Denver, CO",
    distance: 15.7,
    specs: { Material: "ASTM A992 Steel", Size: "W8×31", Length: "20'", Weight: "31 lb/ft", Certification: "Mill Certified" },
    pickupAvailable: true,
    deliveryAvailable: true,
    shippingAvailable: false,
    deliveryCost: 200,
    savedCount: 34,
    viewCount: 189,
    listedAt: "2026-02-26",
    status: "active",
  },
  {
    id: "4",
    title: "Porcelain Floor Tiles — Italian Marble Look",
    description: "Large format porcelain tiles with a stunning Calacatta marble look. Over-ordered for a luxury condo project. Factory sealed boxes, never opened. These are premium grade tiles with rectified edges for minimal grout lines.",
    category: "tile",
    condition: "New Surplus",
    price: 3.50,
    originalPrice: 8.99,
    isFree: false,
    quantity: 520,
    unit: "sq ft",
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800&h=600&fit=crop",
    ],
    seller: sellers[3],
    location: "Miami, FL",
    distance: 8.1,
    specs: { Material: "Porcelain", Size: '24" × 24"', Finish: "Polished", Rating: "PEI 4", Thickness: "10mm" },
    pickupAvailable: true,
    deliveryAvailable: true,
    shippingAvailable: true,
    deliveryCost: 85,
    shippingCost: 180,
    savedCount: 112,
    viewCount: 734,
    listedAt: "2026-02-22",
    status: "active",
  },
  {
    id: "5",
    title: "Copper Plumbing Fittings — Mixed Lot",
    description: "Assorted copper plumbing fittings: elbows, tees, couplings, and reducers in 1/2\" and 3/4\" sizes. All new, unused surplus from a commercial plumbing job. Great value for plumbers stocking up or anyone doing residential copper plumbing work.",
    category: "plumbing",
    condition: "New Surplus",
    price: 0,
    isFree: true,
    quantity: 1,
    unit: "lot",
    images: [
      "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800&h=600&fit=crop",
    ],
    seller: sellers[2],
    location: "Austin, TX",
    distance: 5.3,
    specs: { Material: "Copper", Types: "Elbows, Tees, Couplings", Sizes: '1/2" and 3/4"', "Approx Count": "~150 fittings", Standard: "ASTM B75" },
    pickupAvailable: true,
    deliveryAvailable: false,
    shippingAvailable: false,
    savedCount: 67,
    viewCount: 423,
    listedAt: "2026-02-24",
    status: "active",
  },
  {
    id: "6",
    title: "Commercial LED Panel Lights — 2×4ft",
    description: "High-efficiency LED flat panel lights, 50W each, 5000K daylight color temperature. Brand new in boxes. Surplus from a completed office build-out. UL listed, dimmable, and compatible with standard drop ceilings.",
    category: "electrical",
    condition: "New Surplus",
    price: 35.00,
    originalPrice: 85.00,
    isFree: false,
    quantity: 48,
    unit: "piece",
    images: [
      "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&h=600&fit=crop",
    ],
    seller: sellers[4],
    location: "Seattle, WA",
    distance: 4.8,
    specs: { Type: "LED Flat Panel", Wattage: "50W", "Color Temp": "5000K", Size: '2\' × 4\'', Lumens: "6,250 lm", Dimmable: "Yes" },
    pickupAvailable: true,
    deliveryAvailable: true,
    shippingAvailable: true,
    deliveryCost: 50,
    shippingCost: 120,
    savedCount: 28,
    viewCount: 156,
    listedAt: "2026-02-26",
    status: "active",
  },
  {
    id: "7",
    title: "Concrete Pavers — Charcoal Grey",
    description: "Interlocking concrete pavers in a modern charcoal grey finish. Perfect for patios, walkways, and driveways. These were ordered for a landscaping project that changed design direction. Still on pallets, never laid.",
    category: "concrete",
    condition: "New Surplus",
    price: 2.10,
    originalPrice: 4.50,
    isFree: false,
    quantity: 800,
    unit: "piece",
    images: [
      "https://images.unsplash.com/photo-1590412200988-a436970781fa?w=800&h=600&fit=crop",
    ],
    seller: sellers[5],
    location: "Chicago, IL",
    distance: 12.3,
    specs: { Material: "Concrete", Size: '4" × 8" × 2.375"', Color: "Charcoal Grey", Pattern: "Herringbone Compatible", PSI: "8,000+" },
    pickupAvailable: true,
    deliveryAvailable: true,
    shippingAvailable: false,
    deliveryCost: 150,
    savedCount: 41,
    viewCount: 267,
    listedAt: "2026-02-21",
    status: "active",
  },
  {
    id: "8",
    title: "Architectural Salvage — Solid Wood Doors",
    description: "Collection of salvaged solid wood interior doors from a 1940s craftsman home renovation. Six-panel design, solid fir construction. Some have original hardware. Paint has been stripped from two, others need refinishing. Beautiful craftsmanship you can't find in modern production doors.",
    category: "doors",
    condition: "As-Is",
    price: 75.00,
    originalPrice: 350.00,
    isFree: false,
    quantity: 8,
    unit: "piece",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1520869562399-e772f042f422?w=800&h=600&fit=crop",
    ],
    seller: sellers[7],
    location: "San Francisco, CA",
    distance: 6.7,
    specs: { Material: "Solid Fir", Style: "Six Panel", Height: '80"', Width: '30"–32"', Condition: "Needs refinishing", Era: "1940s" },
    pickupAvailable: true,
    deliveryAvailable: false,
    shippingAvailable: false,
    savedCount: 56,
    viewCount: 389,
    listedAt: "2026-02-20",
    status: "active",
  },
  {
    id: "9",
    title: "R-30 Fiberglass Batt Insulation",
    description: "Kraft-faced fiberglass batt insulation, R-30 value. Ideal for attics and cathedral ceilings. Full bundles, factory wrapped. Over-purchased for an insulation retrofit project. Stored in a dry, climate-controlled warehouse.",
    category: "insulation",
    condition: "New Surplus",
    price: 0,
    isFree: true,
    quantity: 15,
    unit: "bundle",
    images: [
      "https://images.unsplash.com/photo-1607400201889-565b1ee75f8e?w=800&h=600&fit=crop",
    ],
    seller: sellers[0],
    location: "Portland, OR",
    distance: 2.1,
    specs: { Type: "Fiberglass Batt", "R-Value": "R-30", Facing: "Kraft Paper", Width: '15"', Coverage: "88 sq ft/bundle" },
    pickupAvailable: true,
    deliveryAvailable: true,
    shippingAvailable: false,
    deliveryCost: 40,
    savedCount: 23,
    viewCount: 134,
    listedAt: "2026-02-25",
    status: "active",
  },
  {
    id: "10",
    title: "Standing Seam Metal Roofing Panels",
    description: "26-gauge Galvalume standing seam metal roofing panels in a deep forest green. Custom fabricated but project scope reduced. Panels are 16\" wide with 1.5\" seams. Includes matching trim pieces and fasteners. Perfect for barns, workshops, or modern residential roofs.",
    category: "roofing",
    condition: "New Surplus",
    price: 12.50,
    originalPrice: 22.00,
    isFree: false,
    quantity: 45,
    unit: "panel",
    images: [
      "https://images.unsplash.com/photo-1632759145351-1d592919f522?w=800&h=600&fit=crop",
    ],
    seller: sellers[2],
    location: "Austin, TX",
    distance: 7.4,
    specs: { Material: "26ga Galvalume", Color: "Forest Green", Width: '16"', Length: "12'–16'", Seam: '1.5" Standing' },
    pickupAvailable: true,
    deliveryAvailable: true,
    shippingAvailable: false,
    deliveryCost: 100,
    savedCount: 19,
    viewCount: 98,
    listedAt: "2026-02-24",
    status: "active",
  },
  {
    id: "11",
    title: "Benjamin Moore Interior Paint — Assorted Colors",
    description: "Assorted gallons of premium Benjamin Moore Regal Select interior paint. Colors include Simply White, Revere Pewter, Hale Navy, and Classic Gray. All unopened, properly stored. Surplus from a multi-unit residential project. Mix and match!",
    category: "paint",
    condition: "New Surplus",
    price: 32.00,
    originalPrice: 72.00,
    isFree: false,
    quantity: 24,
    unit: "gallon",
    images: [
      "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=800&h=600&fit=crop",
    ],
    seller: sellers[5],
    location: "Chicago, IL",
    distance: 9.8,
    specs: { Brand: "Benjamin Moore", Line: "Regal Select", Finish: "Eggshell", Size: "1 Gallon", Coverage: "400 sq ft/gal" },
    pickupAvailable: true,
    deliveryAvailable: false,
    shippingAvailable: true,
    shippingCost: 25,
    savedCount: 37,
    viewCount: 201,
    listedAt: "2026-02-23",
    status: "active",
  },
  {
    id: "12",
    title: "Brushed Nickel Cabinet Hardware Set",
    description: "Modern brushed nickel cabinet pulls and knobs. 96mm center-to-center pulls and 1.25\" round knobs. Solid zinc alloy construction, heavy and well-made. Purchased for a kitchen renovation that went with a different style.",
    category: "fixtures",
    condition: "New Surplus",
    price: 0,
    isFree: true,
    quantity: 1,
    unit: "set (50 pulls + 20 knobs)",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop",
    ],
    seller: sellers[7],
    location: "San Francisco, CA",
    distance: 5.2,
    specs: { Material: "Zinc Alloy", Finish: "Brushed Nickel", "Pull Size": "96mm CC", "Knob Diameter": '1.25"', Includes: "50 pulls, 20 knobs, screws" },
    pickupAvailable: true,
    deliveryAvailable: false,
    shippingAvailable: true,
    shippingCost: 15,
    savedCount: 45,
    viewCount: 312,
    listedAt: "2026-02-22",
    status: "active",
  },
  {
    id: "13",
    title: "Treated Southern Pine Deck Boards",
    description: "Pressure-treated Southern Yellow Pine deck boards, 5/4×6 profile. Perfect for decking, porches, and outdoor structures. Ground contact rated (UC4A). Kiln dried after treatment for minimal warping. Surplus from a large deck project.",
    category: "lumber",
    condition: "New Surplus",
    price: 3.25,
    originalPrice: 7.80,
    isFree: false,
    quantity: 120,
    unit: "piece",
    images: [
      "https://images.unsplash.com/photo-1541123603104-512919d6a96c?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1520869562399-e772f042f422?w=800&h=600&fit=crop",
    ],
    seller: sellers[3],
    location: "Miami, FL",
    distance: 11.5,
    specs: { Material: "Southern Yellow Pine", Profile: "5/4 × 6", Length: "16'", Treatment: "ACQ (UC4A)", Drying: "KDAT" },
    pickupAvailable: true,
    deliveryAvailable: true,
    shippingAvailable: false,
    deliveryCost: 90,
    savedCount: 31,
    viewCount: 178,
    listedAt: "2026-02-26",
    status: "active",
  },
  {
    id: "14",
    title: "Commercial-Grade Vinyl Plank Flooring",
    description: "Luxury vinyl plank flooring in a natural oak finish. 7mm thick with attached cork underlayment. Waterproof, scratch-resistant, and rated for commercial use. Click-lock installation — perfect for DIYers. Surplus from a restaurant renovation.",
    category: "tile",
    condition: "New Surplus",
    price: 2.15,
    originalPrice: 5.49,
    isFree: false,
    quantity: 650,
    unit: "sq ft",
    images: [
      "https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800&h=600&fit=crop",
    ],
    seller: sellers[1],
    location: "Brooklyn, NY",
    distance: 1.8,
    specs: { Material: "Luxury Vinyl", Thickness: "7mm + 1mm Cork", Width: '7"', Length: '48"', Wear: "20 mil Commercial" },
    pickupAvailable: true,
    deliveryAvailable: true,
    shippingAvailable: true,
    deliveryCost: 60,
    shippingCost: 195,
    savedCount: 78,
    viewCount: 456,
    listedAt: "2026-02-25",
    status: "active",
  },
  {
    id: "15",
    title: "Electrical Wire — 12/2 Romex NM-B",
    description: "250ft rolls of 12/2 NM-B Romex electrical wire. Brand new, still in original packaging. Standard for 20-amp residential circuits. We bought more than needed for a residential wiring project. UL listed, meets all current NEC requirements.",
    category: "electrical",
    condition: "New Surplus",
    price: 65.00,
    originalPrice: 119.00,
    isFree: false,
    quantity: 6,
    unit: "roll (250ft)",
    images: [
      "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&h=600&fit=crop",
    ],
    seller: sellers[4],
    location: "Seattle, WA",
    distance: 3.6,
    specs: { Type: "NM-B (Romex)", Gauge: "12/2 with Ground", Length: "250 ft/roll", Rating: "600V", Listing: "UL Listed" },
    pickupAvailable: true,
    deliveryAvailable: true,
    shippingAvailable: true,
    deliveryCost: 30,
    shippingCost: 45,
    savedCount: 15,
    viewCount: 89,
    listedAt: "2026-02-27",
    status: "active",
  },
  {
    id: "16",
    title: "Corrugated Metal Sheet Panels",
    description: "Galvanized corrugated steel roofing/siding panels. Classic 2.67\" corrugation profile. Great for agricultural buildings, workshops, accent walls, or rustic design elements. Some minor storage scratches but structurally perfect.",
    category: "steel",
    condition: "Lightly Used",
    price: 18.00,
    originalPrice: 35.00,
    isFree: false,
    quantity: 30,
    unit: "sheet",
    images: [
      "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=600&fit=crop",
    ],
    seller: sellers[6],
    location: "Denver, CO",
    distance: 20.3,
    specs: { Material: "Galvanized Steel", Gauge: "29", Size: '26" × 12\'', Profile: '2.67" Corrugated', Coating: "G90 Galvanized" },
    pickupAvailable: true,
    deliveryAvailable: true,
    shippingAvailable: false,
    deliveryCost: 175,
    savedCount: 22,
    viewCount: 145,
    listedAt: "2026-02-21",
    status: "active",
  },
  {
    id: "17",
    title: "Subway Tiles — Classic White 3×6",
    description: "Classic white ceramic subway tiles. Glossy finish, beveled edges. The timeless choice for kitchens and bathrooms. Factory sealed boxes of 100 tiles each. Overstock from a restaurant renovation that scaled down.",
    category: "tile",
    condition: "New Surplus",
    price: 0.45,
    originalPrice: 1.20,
    isFree: false,
    quantity: 2000,
    unit: "piece",
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
    ],
    seller: sellers[5],
    location: "Chicago, IL",
    distance: 7.2,
    specs: { Material: "Ceramic", Size: '3" × 6"', Finish: "Glossy", Edge: "Beveled", Color: "Bright White" },
    pickupAvailable: true,
    deliveryAvailable: true,
    shippingAvailable: true,
    deliveryCost: 40,
    shippingCost: 95,
    savedCount: 93,
    viewCount: 612,
    listedAt: "2026-02-19",
    status: "active",
  },
  {
    id: "18",
    title: "PEX Tubing — 1/2\" Red & Blue Bundle",
    description: "PEX-A tubing in both red (hot) and blue (cold) — 300ft coils of each. Perfect for residential plumbing retrofits or new construction. Expansion fitting compatible. Oxygen barrier rated. Over-ordered for a multi-bathroom renovation.",
    category: "plumbing",
    condition: "New Surplus",
    price: 85.00,
    originalPrice: 165.00,
    isFree: false,
    quantity: 4,
    unit: "coil (300ft)",
    images: [
      "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800&h=600&fit=crop",
    ],
    seller: sellers[2],
    location: "Austin, TX",
    distance: 6.1,
    specs: { Material: "PEX-A", Size: '1/2"', Length: "300 ft/coil", Colors: "Red & Blue available", Standard: "ASTM F876" },
    pickupAvailable: true,
    deliveryAvailable: true,
    shippingAvailable: true,
    deliveryCost: 35,
    shippingCost: 55,
    savedCount: 18,
    viewCount: 112,
    listedAt: "2026-02-24",
    status: "active",
  },
  {
    id: "19",
    title: "Spray Foam Insulation Kits — Closed Cell",
    description: "Two-component closed cell spray foam insulation kits. Each kit covers approximately 200 board feet at 1\" thickness. Great for rim joists, small areas, and spot insulation. Unused, sealed kits with spray guns included.",
    category: "insulation",
    condition: "New Surplus",
    price: 280.00,
    originalPrice: 450.00,
    isFree: false,
    quantity: 3,
    unit: "kit",
    images: [
      "https://images.unsplash.com/photo-1607400201889-565b1ee75f8e?w=800&h=600&fit=crop",
    ],
    seller: sellers[7],
    location: "San Francisco, CA",
    distance: 4.5,
    specs: { Type: "Closed Cell", Coverage: "200 board ft @ 1\"", "R-Value": "R-7 per inch", Components: "A & B + Gun", "Shelf Life": "12 months" },
    pickupAvailable: true,
    deliveryAvailable: false,
    shippingAvailable: false,
    savedCount: 8,
    viewCount: 67,
    listedAt: "2026-02-26",
    status: "active",
  },
  {
    id: "20",
    title: "Scaffolding Frame Set — 5×5ft",
    description: "Standard 5'×5' scaffolding frame sets. Includes frames, cross braces, and base plates. Hot-dip galvanized for corrosion resistance. Used on one project, cleaned and in excellent condition. OSHA compliant.",
    category: "equipment",
    condition: "Lightly Used",
    price: 95.00,
    originalPrice: 210.00,
    isFree: false,
    quantity: 12,
    unit: "set",
    images: [
      "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=600&fit=crop",
    ],
    seller: sellers[6],
    location: "Denver, CO",
    distance: 18.9,
    specs: { Type: "Standard Frame", Size: "5' × 5'", Material: "Galvanized Steel", Includes: "Frames, Braces, Plates", Compliance: "OSHA / ANSI" },
    pickupAvailable: true,
    deliveryAvailable: true,
    shippingAvailable: false,
    deliveryCost: 250,
    savedCount: 14,
    viewCount: 89,
    listedAt: "2026-02-23",
    status: "active",
  },
];

export const orders: Order[] = [
  {
    id: "o1",
    orderNumber: "SLV-2026-0847",
    items: [{ listing: listings[0], quantity: 50 }],
    buyer: { name: "Tom Henderson", email: "tom@hendersonconstruction.com", avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&h=100&fit=crop&crop=face" },
    seller: sellers[0],
    status: "confirmed",
    total: 237.50,
    serviceFee: 17.81,
    createdAt: "2026-02-26",
    logistics: "pickup",
  },
  {
    id: "o2",
    orderNumber: "SLV-2026-0848",
    items: [{ listing: listings[3], quantity: 200 }],
    buyer: { name: "Rachel Kim", email: "rachel@kimdesignstudio.com", avatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=100&h=100&fit=crop&crop=face" },
    seller: sellers[3],
    status: "pending",
    total: 700.00,
    serviceFee: 52.50,
    createdAt: "2026-02-27",
    logistics: "delivery",
  },
  {
    id: "o3",
    orderNumber: "SLV-2026-0843",
    items: [{ listing: listings[1], quantity: 150 }],
    buyer: { name: "Alex Petrov", email: "alex@petrovremodeling.com", avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&h=100&fit=crop&crop=face" },
    seller: sellers[1],
    status: "completed",
    total: 937.50,
    serviceFee: 70.31,
    createdAt: "2026-02-20",
    logistics: "delivery",
  },
  {
    id: "o4",
    orderNumber: "SLV-2026-0845",
    items: [{ listing: listings[5], quantity: 12 }],
    buyer: { name: "Megan Clark", email: "megan@clarkelectric.com", avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&h=100&fit=crop&crop=face" },
    seller: sellers[4],
    status: "ready",
    total: 420.00,
    serviceFee: 31.50,
    createdAt: "2026-02-24",
    logistics: "shipping",
  },
  {
    id: "o5",
    orderNumber: "SLV-2026-0841",
    items: [{ listing: listings[7], quantity: 4 }],
    buyer: { name: "Daniel Rivera", email: "daniel@riveradesign.com", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face" },
    seller: sellers[7],
    status: "completed",
    total: 300.00,
    serviceFee: 22.50,
    createdAt: "2026-02-18",
    logistics: "pickup",
  },
];

export const testimonials = [
  {
    quote: "Salvio saved us over $40,000 on materials for our latest condo project. The quality of surplus materials is incredible — most are brand new, just over-ordered.",
    name: "Jennifer Walsh",
    company: "Walsh Development Group",
    avatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=100&h=100&fit=crop&crop=face",
  },
  {
    quote: "As a small contractor, I used to throw away thousands of dollars in leftover materials. Now I list them on Salvio and recover costs while helping the environment.",
    name: "Mike Tanaka",
    company: "Tanaka Builders",
    avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&h=100&fit=crop&crop=face",
  },
  {
    quote: "The ecological impact tracking is what sets Salvio apart. Our clients love seeing the actual waste diversion numbers on our project reports.",
    name: "Priya Sharma",
    company: "GreenFrame Architecture",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&h=100&fit=crop&crop=face",
  },
];

export const partnerLogos = [
  "Turner Construction",
  "Skanska",
  "Bechtel",
  "Kiewit",
  "Clark Construction",
  "Hensel Phelps",
  "Whiting-Turner",
  "Mortenson",
];
