export function formatPrice(price: number, isFree: boolean = false): string { if (isFree) return "GRATUIT"; return new Intl.NumberFormat("ro-MD", { style: "currency", currency: "MDL", minimumFractionDigits: price % 1 === 0 ? 0 : 2, maximumFractionDigits: 2, }).format(price);
} export function formatDistance(km: number): string { if (km < 1) return `${(km * 1000).toFixed(0)} m`; return `${km.toFixed(1)} km`;
} export function formatNumber(n: number): string { if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`; if (n >= 1_000) return `${(n / 1_000).toFixed(n >= 10_000 ? 0 : 1)}K`; return n.toLocaleString("ro-MD");
} export function formatDate(dateStr: string): string { const date = new Date(dateStr); return date.toLocaleDateString("ro-MD", { month: "short", day: "numeric", year: "numeric", });
} export function getDiscountPercent(price: number, originalPrice: number): number { return Math.round(((originalPrice - price) / originalPrice) * 100);
} export function getConditionColor(condition: string): string { switch (condition) { case "Surplus Nou": return "bg-eco/10 text-eco"; case "Ușor Utilizat": return "bg-mercury-500/10 text-mercury-500"; case "În Starea Actuală": return "bg-amber-100 text-amber-700"; case "Recuperat": return "bg-mercury-500/10 text-mercury-500"; default: return "bg-mercury-500/10 text-mercury-500"; }
} export function estimateImpact(listing: { category: string; quantity: number }): { wasteKg: number; co2Kg: number;
} { const categoryWeights: Record<string, number> = { lumber: 2.5, steel: 8.0, concrete: 12.0, tile: 3.0, electrical: 0.5, plumbing: 1.5, fixtures: 0.8, roofing: 4.0, insulation: 1.0, paint: 4.5, doors: 25.0, equipment: 50.0, }; const weight = categoryWeights[listing.category] || 2.0; const wasteKg = Math.round(listing.quantity * weight); const co2Kg = Math.round(wasteKg * 0.75); return { wasteKg, co2Kg };
} export function cn(...classes: (string | boolean | undefined | null)[]): string { return classes.filter(Boolean).join(" ");
}
